//! Offline validator + self-healing generator for the calibration audio
//! signal fixture set (tone + chirp), used to drive a real output device in
//! CI and feed the strict `live-audio-smoke` signal assertions.
//!
//! Mirrors `aec_vad_fixtures.rs` / `source_separation_fixtures.rs`: parses
//! the checked-in manifest, regenerates any missing WAV from the
//! deterministic synthesizer in [`crate::audio::signal_synth`], and asserts
//! the regenerated bytes are byte-for-byte identical to what is checked in —
//! no audio device, no `live-audio-smoke` feature, no ML feature required.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::audio::signal_synth::{linear_chirp_i16, sine_tone_i16};
use crate::audio::wav_io;

const SAMPLE_RATE_HZ: u32 = 16_000;

#[derive(Debug, Deserialize)]
struct AudioSignalManifest {
    schema_version: u32,
    id: String,
    format: AudioFormat,
    provenance: Provenance,
    fixtures: Vec<Fixture>,
    #[serde(default)]
    speech_fixtures: Vec<SpeechFixture>,
}

#[derive(Debug, Deserialize)]
struct AudioFormat {
    container: String,
    encoding: String,
    sample_rate: u32,
    channels: u16,
    bit_depth: u16,
}

#[derive(Debug, Deserialize)]
struct Provenance {
    kind: String,
    license: String,
    secret_free: bool,
    deterministic: bool,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    id: String,
    kind: FixtureKind,
    audio_path: String,
    duration_ms: u64,
    sha256: String,
    byte_length: u64,
    synthesis: Synthesis,
    expected_signal: ExpectedSignal,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Hash, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum FixtureKind {
    Tone,
    Chirp,
}

#[derive(Debug, Deserialize)]
struct Synthesis {
    freq_hz: Option<f64>,
    start_hz: Option<f64>,
    end_hz: Option<f64>,
    amplitude: f64,
}

#[derive(Debug, Deserialize)]
struct ExpectedSignal {
    rms_floor: f64,
    rms_ceiling: f64,
    max_clipping_rate: f64,
    target_hz: Option<f64>,
    min_single_bin_energy_fraction: Option<f64>,
}

/// A speech fixture composed from existing checked-in LibriSpeech-derived
/// WAVs (see [`Attribution::respects_source_manifest`]) rather than
/// synthesized. Distinct from [`Fixture`] because it carries derivation +
/// attribution instead of a `synthesis` block.
#[derive(Debug, Deserialize)]
struct SpeechFixture {
    id: String,
    kind: String,
    audio_path: String,
    duration_ms: u64,
    sha256: String,
    byte_length: u64,
    derivation: Derivation,
    attribution: Attribution,
    expected_signal: SpeechExpectedSignal,
}

#[derive(Debug, Deserialize)]
struct Derivation {
    method: String,
    segments: Vec<DerivationSegment>,
}

#[derive(Debug, Deserialize)]
struct DerivationSegment {
    role: String,
    #[serde(default)]
    source_path: Option<String>,
    start_ms: u64,
    end_ms: u64,
}

#[derive(Debug, Deserialize)]
struct Attribution {
    source_dataset: String,
    license: String,
    license_url: String,
    homepage_url: String,
    respects_source_manifest: String,
}

#[derive(Debug, Deserialize)]
struct SpeechExpectedSignal {
    rms_floor: f64,
    rms_ceiling: f64,
    max_clipping_rate: f64,
}

#[test]
fn audio_signal_manifest_has_required_fixture_shapes() {
    let manifest = load_manifest();

    assert_eq!(manifest.schema_version, 1);
    assert_eq!(manifest.id, "audio-signal-calibration-mini-v1");
    assert_eq!(manifest.format.container, "wav");
    assert_eq!(manifest.format.encoding, "pcm_s16le");
    assert_eq!(manifest.format.sample_rate, SAMPLE_RATE_HZ);
    assert_eq!(manifest.format.channels, 1);
    assert_eq!(manifest.format.bit_depth, 16);

    assert_eq!(manifest.provenance.kind, "generated");
    assert_eq!(manifest.provenance.license, "repository-owned");
    assert!(manifest.provenance.secret_free);
    assert!(manifest.provenance.deterministic);

    let kinds: std::collections::HashSet<FixtureKind> =
        manifest.fixtures.iter().map(|f| f.kind).collect();
    assert!(
        kinds.contains(&FixtureKind::Tone),
        "must include a tone fixture"
    );
    assert!(
        kinds.contains(&FixtureKind::Chirp),
        "must include a chirp fixture"
    );

    for fixture in &manifest.fixtures {
        assert!(!fixture.id.trim().is_empty());
        assert!(fixture.duration_ms > 0);
        assert_eq!(
            fixture.sha256.len(),
            64,
            "{} sha256 must be 64 hex chars",
            fixture.id
        );
        assert!(
            fixture.sha256.chars().all(|c| c.is_ascii_hexdigit()),
            "{} sha256 must be hex",
            fixture.id
        );
        assert!(
            fixture.byte_length > wav_io::CANONICAL_HEADER_LEN as u64,
            "{} byte_length must exceed the WAV header",
            fixture.id
        );
        assert!(fixture.synthesis.amplitude > 0.0 && fixture.synthesis.amplitude <= 1.0);
        assert!(
            fixture.expected_signal.rms_floor > 0.0,
            "{} rms_floor must be positive (silence must fail)",
            fixture.id
        );
        assert!(
            fixture.expected_signal.rms_floor < fixture.expected_signal.rms_ceiling,
            "{} rms_floor must be below rms_ceiling",
            fixture.id
        );
        assert!(
            fixture.expected_signal.max_clipping_rate > 0.0
                && fixture.expected_signal.max_clipping_rate < 1.0,
            "{} max_clipping_rate must be a small positive fraction",
            fixture.id
        );

        match fixture.kind {
            FixtureKind::Tone => {
                assert!(
                    fixture.synthesis.freq_hz.is_some(),
                    "{} needs freq_hz",
                    fixture.id
                );
                let target_hz = fixture
                    .expected_signal
                    .target_hz
                    .unwrap_or_else(|| panic!("{} tone fixture needs target_hz", fixture.id));
                assert_eq!(
                    target_hz,
                    fixture.synthesis.freq_hz.unwrap(),
                    "{} target_hz must match the synthesized frequency",
                    fixture.id
                );
                let min_fraction = fixture
                    .expected_signal
                    .min_single_bin_energy_fraction
                    .unwrap_or_else(|| {
                        panic!(
                            "{} tone fixture needs min_single_bin_energy_fraction",
                            fixture.id
                        )
                    });
                assert!(
                    min_fraction > 0.0 && min_fraction <= 0.5,
                    "{} min_single_bin_energy_fraction must be in (0.0, 0.5] \
                     (0.5 is the theoretical max for a real-valued single tone)",
                    fixture.id
                );
            }
            FixtureKind::Chirp => {
                assert!(
                    fixture.synthesis.start_hz.is_some(),
                    "{} needs start_hz",
                    fixture.id
                );
                assert!(
                    fixture.synthesis.end_hz.is_some(),
                    "{} needs end_hz",
                    fixture.id
                );
                assert!(
                    fixture.expected_signal.target_hz.is_none(),
                    "{} chirp fixture sweeps frequency; single-bin energy does not apply",
                    fixture.id
                );
                assert!(
                    fixture
                        .expected_signal
                        .min_single_bin_energy_fraction
                        .is_none()
                );
            }
        }
    }
}

#[test]
fn turn_taking_speech_fixture_has_required_derivation_and_attribution() {
    let manifest = load_manifest();
    assert!(
        !manifest.speech_fixtures.is_empty(),
        "manifest must define at least one speech fixture"
    );

    for fixture in &manifest.speech_fixtures {
        assert!(!fixture.id.trim().is_empty());
        assert_eq!(fixture.kind, "turn_taking");
        assert!(fixture.duration_ms > 0);
        assert_eq!(fixture.sha256.len(), 64);
        assert!(fixture.sha256.chars().all(|c| c.is_ascii_hexdigit()));
        assert!(fixture.byte_length > wav_io::CANONICAL_HEADER_LEN as u64);

        // Attribution must point back at the CC-BY LibriSpeech source and at
        // the source_separation manifest it is required to respect.
        assert_eq!(fixture.attribution.license, "CC BY 4.0");
        assert!(
            fixture
                .attribution
                .license_url
                .starts_with("https://creativecommons.org/licenses/by/4.0/")
        );
        assert!(fixture.attribution.homepage_url.contains("openslr.org"));
        assert!(fixture.attribution.source_dataset.contains("LibriSpeech"));
        assert_eq!(
            fixture.attribution.respects_source_manifest,
            "fixtures/source_separation/manifest.json"
        );

        // Derivation segments must be contiguous, ordered, and cover exactly
        // [0, duration_ms) with no gaps or overlaps.
        assert!(!fixture.derivation.method.trim().is_empty());
        assert!(
            fixture.derivation.segments.len() >= 2,
            "{} must derive from at least a speaker segment and a gap/other segment",
            fixture.id
        );
        let mut expected_start = 0u64;
        let mut speaker_segments = 0usize;
        for segment in &fixture.derivation.segments {
            assert_eq!(
                segment.start_ms, expected_start,
                "{} segment {} must start where the previous one ended",
                fixture.id, segment.role
            );
            assert!(segment.start_ms < segment.end_ms);
            if segment.role.starts_with("speaker_") {
                speaker_segments += 1;
                let source_path = segment
                    .source_path
                    .as_deref()
                    .unwrap_or_else(|| panic!("{} speaker segment needs source_path", fixture.id));
                assert!(
                    source_path.starts_with("fixtures/source_separation/audio/"),
                    "{} speaker segment must derive from an existing source_separation WAV, got {source_path}",
                    fixture.id
                );
                assert!(
                    Path::new(env!("CARGO_MANIFEST_DIR"))
                        .join(source_path)
                        .exists(),
                    "{} references a source WAV that does not exist: {source_path}",
                    fixture.id
                );
            }
            expected_start = segment.end_ms;
        }
        assert_eq!(
            expected_start, fixture.duration_ms,
            "{} segments must exactly cover the fixture duration with no gap at the end",
            fixture.id
        );
        assert!(
            speaker_segments >= 2,
            "{} must derive from at least two distinct speaker segments (turn-taking)",
            fixture.id
        );

        assert!(fixture.expected_signal.rms_floor > 0.0);
        assert!(fixture.expected_signal.rms_floor < fixture.expected_signal.rms_ceiling);
        assert!(
            fixture.expected_signal.max_clipping_rate > 0.0
                && fixture.expected_signal.max_clipping_rate < 1.0
        );
    }
}

#[test]
fn turn_taking_speech_wav_matches_manifest_and_recomposes_byte_identically() {
    let manifest = load_manifest();
    ensure_speech_fixtures_generated(&manifest);

    for fixture in &manifest.speech_fixtures {
        let path = fixture_root().join(&fixture.audio_path);
        let on_disk = fs::read(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));

        assert_eq!(
            on_disk.len() as u64,
            fixture.byte_length,
            "{} byte length",
            fixture.id
        );
        assert_eq!(
            sha256_hex(&on_disk),
            fixture.sha256,
            "{} sha256",
            fixture.id
        );

        let decoded = wav_io::decode(&on_disk)
            .unwrap_or_else(|error| panic!("{} failed to decode: {error}", fixture.id));
        assert_eq!(decoded.sample_rate, manifest.format.sample_rate);
        assert_eq!(decoded.channels, manifest.format.channels);
        assert_eq!(
            decoded.duration_ms(),
            fixture.duration_ms,
            "{} duration",
            fixture.id
        );

        let recomposed_a = compose_turn_taking_speech(fixture);
        let recomposed_b = compose_turn_taking_speech(fixture);
        assert_eq!(
            recomposed_a, recomposed_b,
            "{} recomposition is non-deterministic",
            fixture.id
        );
        assert_eq!(
            recomposed_a, on_disk,
            "{} recomposed bytes differ from the checked-in WAV",
            fixture.id
        );

        let rms = signal_rms_i16(&decoded.samples);
        assert!(
            rms >= fixture.expected_signal.rms_floor && rms <= fixture.expected_signal.rms_ceiling,
            "{} computed RMS {rms} is outside the manifest's declared [{}, {}] range",
            fixture.id,
            fixture.expected_signal.rms_floor,
            fixture.expected_signal.rms_ceiling
        );
    }
}

/// Regenerate any missing speech fixture by concatenating its declared
/// derivation segments: real speaker audio read straight from the existing
/// (checked-in, CC-BY-licensed) `source_separation` WAVs, with silence for
/// any non-`speaker_*` segment. The manifest's `derivation.segments` is the
/// single source of truth for both this generator and the schema test above,
/// so a change to the recipe cannot silently desync from what is validated.
fn ensure_speech_fixtures_generated(manifest: &AudioSignalManifest) {
    for fixture in &manifest.speech_fixtures {
        let path = fixture_root().join(&fixture.audio_path);
        if path.exists() {
            continue;
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .unwrap_or_else(|error| panic!("failed to create {}: {error}", parent.display()));
        }
        let bytes = compose_turn_taking_speech(fixture);
        fs::write(&path, bytes)
            .unwrap_or_else(|error| panic!("failed to write {}: {error}", path.display()));
    }
}

fn compose_turn_taking_speech(fixture: &SpeechFixture) -> Vec<u8> {
    let mut samples: Vec<i16> = Vec::new();
    for segment in &fixture.derivation.segments {
        let segment_ms = segment.end_ms - segment.start_ms;
        let segment_samples = ((segment_ms * u64::from(SAMPLE_RATE_HZ)) / 1000) as usize;
        match &segment.source_path {
            Some(source_path) => {
                let source_bytes =
                    fs::read(Path::new(env!("CARGO_MANIFEST_DIR")).join(source_path))
                        .unwrap_or_else(|error| panic!("failed to read {source_path}: {error}"));
                let decoded = wav_io::decode(&source_bytes)
                    .unwrap_or_else(|error| panic!("failed to decode {source_path}: {error}"));
                assert_eq!(
                    decoded.sample_rate, SAMPLE_RATE_HZ,
                    "{source_path} sample rate must match the audio_signal fixture format"
                );
                assert_eq!(decoded.channels, 1, "{source_path} must be mono");
                assert_eq!(
                    decoded.samples.len(),
                    segment_samples,
                    "{source_path} sample count must match its declared segment span"
                );
                samples.extend_from_slice(&decoded.samples);
            }
            None => {
                // Non-speaker segment (e.g. the inter-speaker silence gap).
                samples.extend(std::iter::repeat_n(0i16, segment_samples));
            }
        }
    }
    wav_io::encode(&samples, SAMPLE_RATE_HZ, 1)
}

#[test]
fn audio_signal_wavs_match_manifest_and_regenerate_byte_identically() {
    let manifest = load_manifest();
    ensure_fixtures_generated(&manifest);

    for fixture in &manifest.fixtures {
        let path = fixture_root().join(&fixture.audio_path);
        let on_disk = fs::read(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));

        assert_eq!(
            on_disk.len() as u64,
            fixture.byte_length,
            "{} on-disk byte length must match the manifest",
            fixture.id
        );
        assert_eq!(
            sha256_hex(&on_disk),
            fixture.sha256,
            "{} on-disk SHA-256 must match the manifest",
            fixture.id
        );

        let decoded = wav_io::decode(&on_disk)
            .unwrap_or_else(|error| panic!("{} failed to decode: {error}", fixture.id));
        assert_eq!(decoded.sample_rate, manifest.format.sample_rate);
        assert_eq!(decoded.channels, manifest.format.channels);
        assert_eq!(
            decoded.duration_ms(),
            fixture.duration_ms,
            "{} duration",
            fixture.id
        );

        // Deterministic regeneration: synthesize fresh in-memory bytes twice
        // and assert both equal each other AND the checked-in file. This is
        // the "regenerating must be byte-identical" guarantee — proved, not
        // asserted by fiat.
        let regenerated_a = synthesize_and_encode(fixture);
        let regenerated_b = synthesize_and_encode(fixture);
        assert_eq!(
            regenerated_a, regenerated_b,
            "{} regeneration is non-deterministic",
            fixture.id
        );
        assert_eq!(
            regenerated_a, on_disk,
            "{} regenerated bytes differ from the checked-in WAV",
            fixture.id
        );

        // Sanity-check the manifest's own RMS thresholds against the fixture
        // we just generated, so a bad threshold is caught here rather than
        // only surfacing later inside the device-dependent strict smoke.
        let rms = signal_rms_i16(&decoded.samples);
        assert!(
            rms >= fixture.expected_signal.rms_floor && rms <= fixture.expected_signal.rms_ceiling,
            "{} computed RMS {rms} is outside the manifest's declared [{}, {}] range",
            fixture.id,
            fixture.expected_signal.rms_floor,
            fixture.expected_signal.rms_ceiling
        );
    }
}

/// Regenerate any missing fixture WAV from the deterministic synthesizer so
/// a fresh checkout self-heals and the bytes stay reproducible.
fn ensure_fixtures_generated(manifest: &AudioSignalManifest) {
    for fixture in &manifest.fixtures {
        let path = fixture_root().join(&fixture.audio_path);
        if path.exists() {
            continue;
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .unwrap_or_else(|error| panic!("failed to create {}: {error}", parent.display()));
        }
        let bytes = synthesize_and_encode(fixture);
        fs::write(&path, bytes)
            .unwrap_or_else(|error| panic!("failed to write {}: {error}", path.display()));
    }
}

fn synthesize_and_encode(fixture: &Fixture) -> Vec<u8> {
    let samples = match fixture.kind {
        FixtureKind::Tone => sine_tone_i16(
            fixture
                .synthesis
                .freq_hz
                .expect("tone fixture needs freq_hz"),
            fixture.synthesis.amplitude,
            fixture.duration_ms,
            SAMPLE_RATE_HZ,
        ),
        FixtureKind::Chirp => linear_chirp_i16(
            fixture
                .synthesis
                .start_hz
                .expect("chirp fixture needs start_hz"),
            fixture
                .synthesis
                .end_hz
                .expect("chirp fixture needs end_hz"),
            fixture.synthesis.amplitude,
            fixture.duration_ms,
            SAMPLE_RATE_HZ,
        ),
    };
    wav_io::encode(&samples, SAMPLE_RATE_HZ, 1)
}

fn signal_rms_i16(samples: &[i16]) -> f64 {
    if samples.is_empty() {
        return 0.0;
    }
    let sum_sq: f64 = samples.iter().map(|&s| f64::from(s) * f64::from(s)).sum();
    (sum_sq / samples.len() as f64).sqrt()
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

fn load_manifest() -> AudioSignalManifest {
    let path = fixture_root().join("manifest.json");
    let body = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    serde_json::from_str(&body)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()))
}

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("audio_signal")
}
